version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: project-spring-jpa-shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_spring_jpa_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
